### PR TITLE
update envs to CI

### PR DESCRIPTION
**Pull request by matmuchrapna**
in short: added iojs and nodejs@0.12

### CODE REVIEW

**Comment by matmuchrapna** [comment]
I don’t understand why AppVeyor build failed, sorry =(

**Comment by matmuchrapna** [comment]
polite ping

**Comment by mimetnet** [comment]
Sorry for the delay @matmuchrapna. Your changes are merged into the devel branch with another tweak or two. Once Travis gives me the green light it'll be merged and published.

**Comment by matmuchrapna** [comment]
No, It‘s fine and cool. I definitely like the way it’s processing. Looking forward to see these changes in master =)

**Pull request merged**
